[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flowrhythm"
version = "0.1.0"
description = "Asynchronous job processing framework with dynamic worker scaling"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Andrey Maximov" }]
keywords = ["asyncio", "pipeline", "worker pool", "scaling", "job processing"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: System :: Distributed Computing",
  "Topic :: Software Development :: Libraries",
]

[project.urls]
Homepage = "https://github.com/yourusername/flowrhythm"
Repository = "https://github.com/yourusername/flowrhythm"
Issues = "https://github.com/yourusername/flowrhythm/issues"

[tool.setuptools]
packages = ["flowrhythm"]
include-package-data = true
